# This is a basic workflow to help you get started with Actions

name: Import in production

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  call_webhook:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Call webhook with authentication
        run: |
          echo "Making request to webhook..."
          echo "URL: ${{ secrets.WEBHOOK_URL }}"
          echo "Username: ${{ secrets.WEBHOOK_USERNAME }}"
          
          response=$(curl -v -s -w "\n%{http_code}" \
            -X POST \
            -H "Content-Type: application/json" \
            -u "${{ secrets.WEBHOOK_USERNAME }}:${{ secrets.WEBHOOK_PASSWORD }}" \
            -d "{\"owner\": \"${{ github.repository_owner }}\", \"repository\": \"${{ github.event.repository.name }}\"}" \
            "${{ secrets.WEBHOOK_URL }}" 2>&1)
          
          echo "Full response:"
          echo "$response"
          
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')
          
          if [ "$http_code" -ge 200 ] && [ "$http_code" -lt 300 ]; then
            echo "Webhook call successful (HTTP $http_code)"
            echo "Response body: $body"
          else
            echo "Webhook call failed with HTTP $http_code"
            echo "Response body: $body"
            exit 1
          fi
